---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmatters-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: xmatters-service
  replicas: 1
  template:
    metadata:
      labels:
        run: xmatters-service
    spec:
      containers:
      - name: xmatters-service
        image: msorenson/xmatters-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: XM_EVAL_URL
          value: "https://MY_XM_INSTANCE/api/integration/1/functions/MY_URL_ENCODED_ENDPOINT"
        - name: XM_PROBLEM_URL
          value: "https://MY_XM_INSTANCE/api/integration/1/functions/MY_URL_ENCODED_ENDPOINT"
---
apiVersion: v1
kind: Service
metadata:
  name: xmatters-service
  namespace: keptn
  labels:
    run: xmatters-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: xmatters-service
